/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Information on everything that can be found on the disk
 */
export type Metadata =
  | {
      File: FileMetadata;
    }
  | {
      Folder: FolderMetadata;
    }
  | {
      Link: LinkMetadata;
    };
export type OsString =
  | {
      Unix: number[];
      [k: string]: unknown;
    }
  | {
      Windows: number[];
      [k: string]: unknown;
    };

/**
 * Specifique Information about file
 */
export interface FileMetadata {
  filetype: string;
  size: number;
  sysdata: Sysdata;
  [k: string]: unknown;
}
/**
 * Global "item" Information
 */
export interface Sysdata {
  basename: OsString;
  created_at?: SystemTime | null;
  is_dir: boolean;
  is_hidden: boolean;
  is_link: boolean;
  last_accessed?: SystemTime | null;
  last_modified?: SystemTime | null;
  path: string;
  [k: string]: unknown;
}
export interface SystemTime {
  nanos_since_epoch: number;
  secs_since_epoch: number;
  [k: string]: unknown;
}
/**
 * Specifique Information about a folder
 */
export interface FolderMetadata {
  /**
   * The count of everything that can be found inside
   */
  children: string[];
  sysdata: Sysdata;
  [k: string]: unknown;
}
/**
 * Specifique Information about a link
 */
export interface LinkMetadata {
  path: string;
  sysdata: Sysdata;
  [k: string]: unknown;
}
